# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME

font family JetBrainsMono Nerd Font Propo
font size 13
disable_ligatures never
enable_audio_bell no
#shell_integration no-cursor
cursor_shape block
remember_window_size no 
window_padding_width 40 
cursor_stop_blinking_after 0
cursor_blink_interval 0
background_opacity 0.9
confirm_os_window_close 0

background #1e1e2e

color0 #11111b
color1 #e64553
color2 #40a02b
color3 #df8e1d
color4 #1e66f5
color5 #8839ef
color6 #179299
color7 #dce0e8


color8 #1e1e2e
color9 #ea999c
color10 #a6d189
color11 #e5c890
color12 #8caaee
color13 #ca9ee6
color14 #81c8be 
color15 #eff1f5
