background = rgba(23,18,34,0.95)
accent = rgb(226, 19, 211) 
accent_secondary =  rgb(13,6,18)
text = rgb(255,255,255)
base = rgba(23,18,34, 0.95) 
alternate_base = rgb(24,19,35)
icon_theme = "Qogir-Dark"
font_family = "JetBrainsMono Nerd Font Propo" 
font_family_monospace = "JetBrainsMono Nerd Font Propo"

